### ISSUE TITLE
add keyboard shortcut for functions

### ISSUE THREAD

**Issue by SaharZehavi** [doobleweb/sublime-dooble#30]
add/goto item
add/goto config
etc..

don't forget to check which shortcut are free first.

**Comment by SaharZehavi** [comment]
if you wnat to know what's free and how to describe each shortcut, you can use:

sublime.log_input(True)
sublime.log_commands(True)

**Comment by AvitanI** [comment]
Go to module shortcut set to ctrl + keypad 4
Go to item shortcut set to ctrl + keypad 7
Go to master shortcut set to ctrl + keypad 8
Go to config shortcut set to ctrl + keypad 9
