### ISSUE TITLE
Duplicate file function

### ISSUE THREAD

**Issue by SaharZehavi** [doobleweb/sublime-dooble#31]
on the side bar, or context menu, there should be an option to duplicate an item. this should create a new file, with the same content but with a "@" prefix on it name so "master.html" will create "@master.html" but will have the same content.

**Comment by SaharZehavi** [comment]
Instead of adding @ to each file, add the extention ".disabled"
master.html 
will become
master.html.disabled

**Comment by AvitanI** [comment]
Done.
